version: 2

models:
  - name: stg_content__articles
    description: 'Staging model for articles.'
    config:
      tags: ['staging','content']
    columns:
      - name: article_id
        description: '{{ doc("article_id") }}'
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: uuid
      - name: article_title
        description: '{{ doc("article_title") }}'
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: text
          - dbt_expectations.expect_column_value_lengths_to_be_between:
              arguments:
                min_value: 10
                max_value: 80

      - name: slug
        description: '{{ doc("slug") }}'
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: text
          - dbt_expectations.expect_column_value_lengths_to_be_between:
              arguments:
                min_value: 10
                max_value: 80      
      - name: article_short_description
        description: '{{ doc("article_short_description") }}'
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: text
          - dbt_expectations.expect_column_value_lengths_to_be_between:
              arguments:
                min_value: 50
                max_value: 300      
      - name: article_body
        description: "The content of the article."
      - name: article_image
        description: "The hero image associated with the article."
      - name: taxonomies
        description: "The taxonomies the article belongs to."
      - name: created_at
        description: "A timestamp that indicates when the article was created."
      - name: updated_at
        description: "A timestamp that indicates when the article was last updated."
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: timestamp with time zone
